# Generated by Django 3.0.5 on 2020-04-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('сoefficients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('percent', models.FloatField(verbose_name='процент')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('commerce_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='сoefficients.CommerceValue')),
            ],
            options={
                'verbose_name': 'Коэффициет',
                'verbose_name_plural': 'Коэффициеты',
            },
        ),
    ]
