# Generated by Django 3.0.5 on 2020-07-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Коммерческая ценность',
                'verbose_name_plural': 'Коммерческие ценности',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('percent', models.FloatField(verbose_name='процент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('commerce_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coefficients.CommerceValue')),
            ],
            options={
                'verbose_name': 'Коэффициет',
                'verbose_name_plural': 'Коэффициеты',
            },
        ),
    ]
