# Generated by Django 3.0.5 on 2020-04-29 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='денежная сумма')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='currencies.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Customer')),
                ('exchange_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_currency', to='currencies.Currency')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'purchases',
            },
        ),
    ]
